// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://gtsyopcogzuegvakpdky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0c3lvcGNvZ3p1ZWd2YWtwZGt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2NzQ3MzUsImV4cCI6MjA3NjI1MDczNX0.KRQpAYvrq6y2hqRw7VmBQ3cSz3KlnYOWaMpI5gx2Joo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);