name: CI + Telegram post-build notification

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # ✅ Fix: enable corepack and install pnpm
      - name: Enable corepack and install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          pnpm --version

      - name: Install dependencies
        run: pnpm install

      # (Optional) Add your build step if needed
      # - name: Build project
      #   run: pnpm build

      # ✅ Telegram notification after build
      - name: Notify via Telegram
        if: always()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          if [ -z "$TELEGRAM_BOT_TOKEN" ] || [ -z "$TELEGRAM_CHAT_ID" ]; then
            echo "❌ Telegram secrets not configured. Skipping notification."
            exit 0
          fi

          MESSAGE="✅ CI completed for commit $GITHUB_SHA on branch $GITHUB_REF_NAME"
          echo "Sending Telegram message: $MESSAGE"

          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d text="$MESSAGE" \
            -d disable_web_page_preview=true