name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install
        run: pnpm install

      - name: Build (if applicable)
        run: pnpm run build || echo "no build step"

      - name: Smoke test (check env)
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          echo "TELEGRAM_BOT_TOKEN is ${TELEGRAM_BOT_TOKEN:+set}"